# Generated by Django 4.2.17 on 2024-12-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_customuser_rubro_usuario_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='clinicas',
            field=models.ManyToManyField(to='clinica.clinica'),
        ),
    ]
