# Generated by Django 4.2.17 on 2025-01-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_customuser_clinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='obras_sociales',
            field=models.ManyToManyField(blank=True, null=True, to='clinica.obrasocial', verbose_name='obras_sociales'),
        ),
    ]
