# Generated by Django 4.2.17 on 2025-01-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0010_remove_bloqueohorarioprofesional_desde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='obras_sociales',
            field=models.ManyToManyField(blank=True, to='clinica.obrasocial', verbose_name='obras_sociales'),
        ),
    ]
