# Generated by Django 4.2.17 on 2025-01-14 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0011_alter_profesional_obras_sociales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='fecha_desde',
            field=models.DateField(default=datetime.datetime(2025, 1, 14, 22, 57, 18, 908183, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='fecha_hasta',
            field=models.DateField(default=datetime.date(2025, 1, 14)),
            preserve_default=False,
        ),
    ]
