# Generated by Django 4.2.17 on 2025-01-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0012_remove_transactionlog_duracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='borrar_habilitaciones',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
