# Generated by Django 4.2.17 on 2025-01-23 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0013_transactionlog_borrar_habilitaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.profesional', verbose_name='profesional'),
        ),
    ]
